fix: rebuild example-host/add.wasm from tutorial/adder project (#333)
```sh
$ cargo run --release -- 1 2 add.wasm
    Finished `release` profile [optimized] target(s) in 0.14s
     Running `target/release/example-host 1 2 add.wasm`
Error: Failed to instantiate the example world

Caused by:
    no exported instance named `docs:adder/add@0.1.0`
$ cp ../tutorial/adder/target/wasm32-wasip2/release/adder.wasm add.wasm
$ cargo run --release -- 1 2 add.wasm
    Finished `release` profile [optimized] target(s) in 0.10s
     Running `target/release/example-host 1 2 add.wasm`
1 + 2 = 3
```

context

```wit
//wasm-tools component wit example-host/add.wasm
package root:component;

world root {
  export add: func(x: s32, y: s32) -> s32;
}

//cat tutorial/wit/adder/world.wit
package docs:adder@0.1.0;

interface add {
    add: func(x: u32, y: u32) -> u32;
}

world adder {
    export add;
}
```